version: '3.1'
services:
  proxy-service:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  stuff-service:
    build: ./stuff
    environment:
      - TEST_VAL
      - DYNDEPLOY_DOMAIN

  goods-service:
    build: ./stuff
    command: python alt-server.py
    environment:
      - TEST_VAL
      - DYNDEPLOY_DOMAIN
